<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Customer_model extends CI_Model
{

    public $table = 'data_cus_aktif';
    public $id = 'id_cus_aktif';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_cus_aktif', $q);
    $this->db->or_like('nama_lengkap', $q); 

    $this->db->or_like('jk_aktif', $q); 
    $this->db->or_like('no_hp', $q); 
    $this->db->or_like('tgl_lahir', $q); 
    $this->db->or_like('gaji_saat_ini', $q); 
    $this->db->or_like('jangka_pinjam_max', $q); 
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data() {
      $this->db->select('t1.*,t2.*');
        $this->db->from('data_cus_aktif as t1');
        $this->db->join('cabang as t2','t1.id_cabang=t2.id_cabang');
                $this->db->order_by('id_cus_aktif','DESC');
        $query = $this->db->get();
        return $query->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Customer_model.php */
/* Location: ./application/models/Customer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-24 19:34:19 */
/* http://harviacode.com */