<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tugas_model extends CI_Model
{

    public $table = 'tugas';
    public $id = 'id_tugas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    public function listing() {
        $this->db->select('tugas.*,
                           karyawan.*,cabang.*,
                           bidang.*');
        $this->db->from('tugas');
        $this->db->join('karyawan','karyawan.id_karyawan = tugas.id_karyawan','LEFT');

        $this->db->join('cabang','karyawan.id_cabang = cabang.id_cabang','LEFT');
        $this->db->join('bidang','bidang.id_bidang = karyawan.id_bidang','LEFT');  
        $this->db->order_by('id_tugas','DESC');
        $query = $this->db->get();
        return $query->result();
    }

             public function karyawan() {
        $this->db->select('karyawan.*,
                           bidang.*');
        $this->db->from('karyawan');
        $this->db->join('bidang','bidang.id_bidang = karyawan.id_bidang','LEFT'); 
        // $this->db->where('bidang.bagian_karyawan', 'Programmer' AND 'Blogger' );
        $this->db->order_by('id_karyawan','DESC');
        $query = $this->db->get();
        return $query->result();
    }

            // Detail
    public function detail($id_tugas) {
        $this->db->select('*');
        $this->db->from('tugas');
        $this->db->where('id_tugas',$id_tugas);
        $this->db->order_by('id_tugas','DESC');
        $query = $this->db->get();
        return $query->row();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_tugas', $q);
	$this->db->or_like('tanggal_kirim_tugas', $q);
	$this->db->or_like('id_karyawan', $q);
	$this->db->or_like('keterangan_tugas', $q);
	$this->db->or_like('deadline', $q);
	$this->db->or_like('file', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tugas', $q);
	$this->db->or_like('tanggal_kirim_tugas', $q);
	$this->db->or_like('id_karyawan', $q);
	$this->db->or_like('keterangan_tugas', $q);
	$this->db->or_like('deadline', $q);
	$this->db->or_like('file', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tugas_model.php */
/* Location: ./application/models/Tugas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-24 19:34:40 */
/* http://harviacode.com */