<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Wa extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Wa_model');
        // $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'wa/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'wa/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'wa/index.html';
            $config['first_url'] = base_url() . 'wa/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Wa_model->total_rows($q);
        $wa = $this->Wa_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'wa_data' => $wa,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,

            'title'      =>'Data Wa',
            'isi'        =>'admin/wa/wa_list');

             $this->load->view('admin/layout/wrapper', $data, FALSE); 
    }

    public function read($id) 
    {
        $row = $this->Wa_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_wa' => $row->id_wa,
		'nomor_wa' => $row->nomor_wa, 

        'title'      =>'Detail Data Wa',
        'isi'        =>'admin/wa/wa_read');

        $this->load->view('admin/layout/wrapper', $data, FALSE); 
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('admin/wa'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Simpan',
            'action' => base_url('admin/wa/create_action'),
	    'id_wa' => set_value('id_wa'),
	    'nomor_wa' => set_value('nomor_wa'), 

       'title'          =>'Tambah Data Wa',
       'isi'            =>'admin/wa/wa_form');

       $this->load->view('admin/layout/wrapper', $data, FALSE); 
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nomor_wa' => $this->input->post('nomor_wa',TRUE), 
	    );

            $this->Wa_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(base_url('admin/wa'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Wa_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => base_url('admin/wa/update_action'),
		'id_wa' => set_value('id_wa', $row->id_wa),
		'nomor_wa' => set_value('nomor_wa', $row->nomor_wa), 

        'title'                =>'Edit Data Wa',
        'isi'                  =>'admin/wa/wa_form');

        $this->load->view('admin/layout/wrapper', $data, FALSE);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('admin/wa'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_wa', TRUE));
        } else {
            $data = array(
		'nomor_wa' => $this->input->post('nomor_wa',TRUE), 
	    );

            $this->Wa_model->update($this->input->post('id_wa', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(base_url('admin/wa'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Wa_model->get_by_id($id);

        if ($row) {
            $this->Wa_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(base_url('admin/wa'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('admin/wa'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nomor_wa', 'Nomor Wa', 'trim|required'); 

	$this->form_validation->set_rules('id_wa', 'id_wa', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Cabang.php */
/* Location: ./application/controllers/Cabang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-24 19:34:19 */
/* http://harviacode.com */